# Generated by Django 4.2.29 on 2026-04-06 22:27

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
